### ISSUE TITLE
Feedback Modelproject

### ISSUE THREAD

**Issue by bkr361** [NumEconCopenhagen/projects-2020-apollo-17#11]
1. The best part of the project was: (explain what and why)
Your project is a very thorough project where you cover a lot of aspect of the model.

2. The hardest part of the project to understand was: (explain what)
The hardest part of the project was reading your results from your figures. It would be nice if you printed the results as it is hard for the reader to see the exact results from your figures. A good example is figure 2 and 3 where I couldn't see that the results were precisely 0.11

3. This part of the project could be better documented: (explain what)
You should comment more on your figure 4 of Fi as you dont have any comments on them it seems as if you just put them in to show that you can.

4. An idea for an improvement/clarification could be: (explain what and why)
You should make your figures full size so you can see the whole figure when examining it instead of having to scroll. To make it easier for the reader you should point out that the "Results across Parametrisations" is for the bisectional solution and that it is done for the extended model.

5. An idea for an extension could be: (explain what and why)
You could consider making the figures interactive, such that you could see the effect of a change in alpha or fi in both models.

**Comment by signehaahr** [comment]
Thanks for the feedback, it was very useful!
