### ISSUE TITLE
Feedback - Model Analysis 

### ISSUE THREAD

**Issue by zqv124** [NumEconCopenhagen/projects-2020-apollo-17#12]
The best part of the project was:
Your markdowns - explaining what you do at each step. I also think it is nice that you use the print(f' ) function. 

The hardest part of the project to understand was:
It is not hard to understand, but your figures are not full size, which makes them harder to see. 

This part of the project could be better documented:
You define your symbols multiple times - might want to check on this. 

An idea for an improvement/clarification could be:
You could improve the project by adding widgets and making your graphs interactive. I think it is a really nice way of letting the reader examine the model by themselves. 

Also I think you should call the analytical and numerical solutions together,  to show that they are the same. 

An idea for an extension could be:
Your project is quite extensive so no need to add more.

**Comment by signehaahr** [comment]
Thanks for the feedback!
