### ISSUE TITLE
Peerfeedback - model project

### ISSUE THREAD

**Issue by henrikkyndal** [NumEconCopenhagen/projects-2020-apollo-17#13]
1.	The best part of the project was: (explain what and why) 
Generally, you have made a nice and well-structured project. A general comment is that there are several unnecessary words even though this has nothing to do with the ‘coding’. For instance, just write: we extend the model with a more realistic production functions instead of a “bit” more realistic. Besides that, your introduction does the job as it should. 
The best part of the project is definitely the numerical solution part when you analyze a production function with decreasing marginal product of labour! Here you demonstrate that you are good at coding and documenting!

2.	The hardest part of the project to understand was: (explain what) 
Your project was not difficult to understand. That being said, you could consider to be more explicit telling the reader that now you make use of the functions specified in the .py file.

3.	This part of the project could be better documented: (explain what) 
You could make a comment or two on the different equations, when you describe your model settings. Furthermore, you should write “optimization” problem instead of “maximization”.

4.	An idea for an improvement/clarification could be: (explain what and why)
You could consider deleting your first numerical solution part. As you say yourself, it is very easy to calculate it without any python functions. In “the real world” you would never make use of this to such an easy exercise.

5. An idea for an extension could be: (explain what and why)
In general, you may consider making your figures more interactive. In doing so, it is easy for the reader to get the intuition if they try to change the values themselves. As an example, you could consider combining your analyze of the parametrisations. You could make 2 figures which are both interactive. On the vertical axis you could have: “Equilibrium real wage rate” and in the other figure: “Equilibrium labour” then you could change the values of \phi and \alpha using a “slider”.

**Comment by signehaahr** [comment]
Thanks for the feedback!
