### ISSUE TITLE
Peer feedback - Model project

### ISSUE THREAD

**Issue by amanda-em** [NumEconCopenhagen/projects-2020-apollo-17#14]
**1. The best part of the project was:**
Overall, I think your project is very well done. It is well documented and easy to follow what you are trying to do as you write a lot of text explaining your process and results. I like that you solve both the simple model with constant MP and the extended the model with decreasing MP, this makes your analysis quite thorough.

 **2. The hardest part of the project to understand was:**
Some of your figures (figure 1,2,3) are printed in a way where I can’t see the whole figure at the same time (I have to scroll). This makes the figures a little hard to read.

 **3. This part of the project could be better documented:**
The section “Results across Parametrisations” could be explained a little better. Especially in the last two figures, I think you could be a little more explicit about what you change and what the results show. Other than that, I think your project is well documented. 

 **4. An idea for an improvement/clarification could be:**
You could make some of your figures interactive with sliders that change the parameters of the model, so you can see how the curves and solutions change for different values of phi, alpha and epsilon. This could be instead of/an extension to the “Results across Parametrisations” section.

**5. An idea for an extension could be:**
As written above, you could extend with some interactive figures.

**Comment by signehaahr** [comment]
Thanks for the feedback, it was very helpful!
