### ISSUE TITLE
Peer Feedback model project

### ISSUE THREAD

**Issue by PhilipHass** [NumEconCopenhagen/projects-2020-apollo-17#15]
The best part was:
Your project is overall very thorough and well-made.

The hardest part to understand was:
Nothing was truly hard to understand - your code is mostly similar to stuff that's been covered in the course.

This part could be better documented:
Although I think your documentation is overall a little on the light side - I don't think it's a problem, since your code never gets too crazy.

And idea for improvement:
When you create the figures some text shows up above the plot:
"Text(0.5, 1.0 ..."
You should be able to get rid of this, by typing ";" at the end of the last line of code in that cell.

An idea for extension:
Your project is already lengthy, so I think it might be overkill to add a lot more, but you could try making some of the figures interactive.

**Comment by signehaahr** [comment]
Thanks for the feedback, it was very useful! Didn't know the trick with ";" in the end of the line
