### ISSUE TITLE
Peer Feedback - model project

### ISSUE THREAD

**Issue by Katrine0207** [NumEconCopenhagen/projects-2020-apollo-17#16]
**1. The best part of the project was:** 
There is a really good structure throughout the project and it's really nice that you comment on all the functions and figures. it makes it easy to understand.

**2. The hardest part of the project to understand was:** 
As mentioned above. the project is really easy to follow and understand. However, I don't know if it's just me but I think you maybe made a minor mistake when you explain the bisection method in step 3. You set up two cases but both says "if f(b_0)f(m_0) < 0"?

**3. This part of the project could be better documented:**
I think the whole project is well documented and you explain all you steps so I have no further comments here.

**4. An idea for an improvement/clarification could be:** 
I don't know if it is only in my notebook but when I run the code to the three first figures it pops up in a box where you can't see all of it, so you have to scroll a little down to see all of it. This is not the case in the last three which is nice. I don't know why but it could nice if you could see the whole figure when you run the code.

**5. An idea for an extension could be:** 
I don't think your model project need any further extensions. You made a good project. That being said, if you want to add anything you could maybe make some of the figures interactive. It gives a good understanding when you can set and change the values yourself :-)

**Comment by signehaahr** [comment]
Thanks for the feedback, it was very useful!
